#!/usr/bin/env python3
"""Generate embedded bitmap fonts from a TTF for the e-paper dashboard.

Renders ASCII 32..126 at fixed pixel heights (16 and 24) into 1-bit
bitmaps with per-glyph proportional advances, and writes them as C data:
src/gfx/font_data.c and include/gfx/font_data.h.

Usage: python tools/gen_font.py path/to/Font.ttf
"""
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
HEADER = "/*\n** Charles Le Maux, 2026\n** epaper_dashboard\n"


def pick_size(ttf, target):
    size = target
    while size > 4:
        ascent, descent = ImageFont.truetype(ttf, size).getmetrics()
        if ascent + descent <= target:
            return size
        size -= 1
    raise SystemExit("no usable size for height %d" % target)


def render_glyph(font, height, ch):
    advance = max(1, round(font.getlength(ch)))
    bbox = font.getbbox(ch)
    width = max(advance, math.ceil(bbox[2]) if bbox else 1, 1)
    img = Image.new("L", (width, height), 0)
    ImageDraw.Draw(img).text((0, 0), ch, fill=255, font=font)
    px = img.load()
    rows = []
    for y in range(height):
        bits = 0
        for x in range(width):
            bits = (bits << 1) | (1 if px[x, y] >= 128 else 0)
        bits <<= (8 - width % 8) % 8
        rows.append(bits.to_bytes((width + 7) // 8, "big"))
    return advance, width, b"".join(rows)


def build_font(ttf, target):
    font = ImageFont.truetype(ttf, pick_size(ttf, target))
    glyphs, blob = [], bytearray()
    for code in range(FIRST, LAST + 1):
        advance, width, data = render_glyph(font, target, chr(code))
        glyphs.append((len(blob), width, advance))
        blob.extend(data)
    return glyphs, bytes(blob)


def emit_bytes(out, blob):
    for i in range(0, len(blob), 12):
        chunk = ", ".join("0x%02x" % b for b in blob[i:i + 12])
        out.append("    " + chunk + ",")


def emit_font(out, name, height, glyphs, blob):
    out.append("static const struct gfx_glyph %s_GLYPHS[] = {" % name)
    for off, width, adv in glyphs:
        out.append("    {%u, %u, %u}," % (off, width, adv))
    out.append("};")
    out.append("")
    out.append("static const uint8_t %s_BITMAP[] = {" % name)
    emit_bytes(out, blob)
    out.append("};")
    out.append("")
    out.append("const struct gfx_font GFX_FONT_%d = {" % height)
    out.append("    %d, %s_GLYPHS, %s_BITMAP" % (height, name, name))
    out.append("};")


def write_c(root, fonts):
    out = [HEADER + "** File description:",
           "** Generated by tools/gen_font.py from Questrial-Regular.ttf",
           "** (SIL OFL 1.1, see lib/questrial/OFL.txt) - do not edit",
           "*/", "", "#include \"font_data.h\"", ""]
    for name, height, glyphs, blob in fonts:
        emit_font(out, name, height, glyphs, blob)
        out.append("")
    path = root / "src" / "gfx" / "font_data.c"
    path.write_text("\n".join(out).rstrip("\n") + "\n", newline="\n")
    print("wrote", path, "(%d lines)" % len(out))


def write_h(root):
    out = [HEADER + "** File description:",
           "** Generated bitmap font data (Questrial), see tools/gen_font.py",
           "*/", "",
           "#ifndef FONT_DATA_H_", "    #define FONT_DATA_H_", "",
           "    #include <stdint.h>", "",
           "struct gfx_glyph {",
           "    uint16_t offset;",
           "    uint8_t width;",
           "    uint8_t advance;",
           "};", "",
           "struct gfx_font {",
           "    int height;",
           "    struct gfx_glyph const *glyphs;",
           "    uint8_t const *bitmap;",
           "};", "",
           "extern const struct gfx_font GFX_FONT_16;",
           "extern const struct gfx_font GFX_FONT_24;", "",
           "#endif /* !FONT_DATA_H_ */"]
    path = root / "include" / "gfx" / "font_data.h"
    path.write_text("\n".join(out) + "\n", newline="\n")
    print("wrote", path)


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    root = Path(__file__).resolve().parent.parent
    fonts = []
    for name, height in (("Q16", 16), ("Q24", 24)):
        glyphs, blob = build_font(sys.argv[1], height)
        fonts.append((name, height, glyphs, blob))
        print("font %dpx: %d glyphs, %d bytes" % (height, len(glyphs),
                                                  len(blob)))
    write_c(root, fonts)
    write_h(root)


if __name__ == "__main__":
    main()
