#!/usr/bin/env python3
"""Generate embedded 32x32 activity-type icons from Font Awesome Free.

Rasterizes a fixed set of glyphs into 1-bit 32x32 cells and writes them
as C data reusing the gfx_font structures: src/gfx/icon_data.c and
include/gfx/icon_data.h.

Usage: python tools/gen_icons.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

CELL = 32
ICONS = [
    ("ICON_TODO", 0xf00c),
    ("ICON_MAIL", 0xf0e0),
    ("ICON_CALL", 0xf095),
    ("ICON_MEETING", 0xf073),
    ("ICON_INBOX", 0xf01c),
    ("ICON_DOCUMENT", 0xf15b),
    ("ICON_CERTIFICATE", 0xf0a3),
    ("ICON_SIGNATURE", 0xf5b7),
    ("ICON_CLOCK", 0xf017),
]
HEADER = "/*\n** Charles Le Maux, 2026\n** epaper_dashboard\n"


def render_icon(font, code):
    img = Image.new("L", (CELL, CELL), 0)
    draw = ImageDraw.Draw(img)
    left, top, right, bottom = font.getbbox(chr(code))
    x = (CELL - (right - left)) // 2 - left
    y = (CELL - (bottom - top)) // 2 - top
    draw.text((x, y), chr(code), fill=255, font=font)
    px = img.load()
    rows = []
    for row in range(CELL):
        bits = 0
        for col in range(CELL):
            bits = (bits << 1) | (1 if px[col, row] >= 128 else 0)
        rows.append(bits.to_bytes(CELL // 8, "big"))
    return b"".join(rows)


def emit_c(root, blobs):
    out = [HEADER + "** File description:",
           "** Generated by tools/gen_icons.py from Font Awesome Free",
           "** (icons CC BY 4.0, font SIL OFL 1.1, see lib/fontawesome)",
           "*/", "", "#include \"icon_data.h\"", "",
           "static const struct gfx_glyph ICON_GLYPHS[] = {"]
    for i in range(len(blobs)):
        out.append("    {%u, %u, %u}," % (i * CELL * CELL // 8, CELL,
                                          CELL))
    out.append("};")
    out.append("")
    out.append("static const uint8_t ICON_BITMAP[] = {")
    blob = b"".join(blobs)
    for i in range(0, len(blob), 12):
        out.append("    " + ", ".join("0x%02x" % b
                                      for b in blob[i:i + 12]) + ",")
    out.append("};")
    out.append("")
    out.append("const struct gfx_font GFX_ICONS_32 = {")
    out.append("    %d, ICON_GLYPHS, ICON_BITMAP" % CELL)
    out.append("};")
    path = root / "src" / "gfx" / "icon_data.c"
    path.write_text("\n".join(out) + "\n", newline="\n")
    print("wrote", path)


def emit_h(root):
    out = [HEADER + "** File description:",
           "** Generated activity-type icon data, see tools/gen_icons.py",
           "*/", "",
           "#ifndef ICON_DATA_H_", "    #define ICON_DATA_H_", "",
           "    #include \"font_data.h\"", "",
           "enum gfx_icon_id {"]
    for name, _ in ICONS:
        out.append("    %s," % name)
    out += ["};", "",
            "extern const struct gfx_font GFX_ICONS_32;", "",
            "#endif /* !ICON_DATA_H_ */"]
    path = root / "include" / "gfx" / "icon_data.h"
    path.write_text("\n".join(out) + "\n", newline="\n")
    print("wrote", path)


def main():
    root = Path(__file__).resolve().parent.parent
    ttf = root / "lib" / "fontawesome" / "fa-solid-900.ttf"
    font = ImageFont.truetype(str(ttf), 28)
    blobs = [render_icon(font, code) for _, code in ICONS]
    emit_c(root, blobs)
    emit_h(root)
    print("icons: %d, %d bytes" % (len(blobs), len(blobs) * CELL * 4))


if __name__ == "__main__":
    main()
